### ISSUE TITLE
'Pushing' ATIS letter to other controllers

### ISSUE THREAD

**Issue by rt-2** [goliver1984/afv-issues#20]
Hi,
I'm not sure if it's a known bug, but in Euroscope by default you need to press 'Test URL' to update your ATIS letter to others. The problem is that the function only works if "Start Multiple Playback" is pressed.
Its a design error on top of another, but with AFV, "Start Multiple Playback" is always OFF.
Possible solution (dirty): enable "Start Multiple Playback" for half of a second after pressing 'Test URL';
Better solution: Add the function into the AFV UI.
Another solution: Not sure is possible but maybe create a .cmd for example `.pushatis` or smth.

Thank you,
rt-2

**Comment by goliver1984** [comment]
Moved to master AFV Issues list.
