### ISSUE TITLE
How do I create an ATIS

### ISSUE THREAD

**Issue by goliver1984** [goliver1984/afv-issues#9]
We currently have a bot server that picks up any Euroscope Text ATIS, see the instructions on how to do this.

A vATIS Beta with AFV integration is now available for download on the AFV website.

**Comment by rt-2** [comment]
Hi, I can't seem to find the exact documentation or information. I'm trying to tame the integrated voice atis recorder. Is it vATIS? I have not been able to do simple stuff like parsing numbers for example.  have looked at the 'beta' documents for  vATIS, there seem to be other operators.
Thank you

**Comment by prryplatypus** [comment]
Hi @rt-2! Please use the VATSIM Forums for support.
vATIS Section: https://forums.vatsim.net/viewforum.php?f=135
